### ISSUE TITLE
Serverside Crash - No Server External Image Handler

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Wyn-Price/cloak#5]
https://gist.github.com/P3rf3ctXZer0/3a198561ed2f8ca92be3d412e4b101d7

**Comment by Wyn-Price** [comment]
I've fixed this in my workspace, however I'm currently rewriting a massive part of the rendering system, and adding support to render custom block models, and .tbl files, and am right in the middle of doing so. I'll hopefully be able to release a new version soon.

**Comment by P3rf3ctXZer0** [comment]
Awesome thank you :)

**Comment by Wyn-Price** [comment]
@P3rf3ctXZer0 rendering system should be finished up today or tommorow. Sorry for keeping you waiting
